USE icetxx;

DROP TABLE IF EXISTS icetxx.comportamiento_cartera_limpio;

CREATE TABLE icetxx.comportamiento_cartera_limpio AS
SELECT 
    *,
    CAST(REPLACE(REPLACE(REPLACE(`SALDO CAPITAL`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `SALDO_CAPITAL_NUMERICO`,
    CAST(REPLACE(REPLACE(REPLACE(`SALDO TOTAL`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `SALDO_TOTAL_NUMERICO`,
    CAST(REPLACE(REPLACE(REPLACE(`SALDO MORA`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `SALDO_MORA_LIMPIO`,
    CAST(REPLACE(REPLACE(REPLACE(`CANTIDAD CREDITOS AL DIA`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `CANTIDAD_CREDITO_AL_DIA_N`,
    CAST(REPLACE(REPLACE(REPLACE(`CANTIDAD CREDITOS CON MORA MENOR A 90 DIAS`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `CANTIDAD_CREDITOS_CON_MORA_MENOR_A_90_DIAS_N`,
    CAST(REPLACE(REPLACE(REPLACE(`CANTIDAD CREDITOS MORA MAYOR A 90 DIAS`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `CANTIDAD_CREDITOS_MORA_MAYOR_A_90_DIAS_N`,
    CAST(REPLACE(REPLACE(REPLACE(`TOTAL CREDITOS`, '$', ''), ',', ''), '.', '') AS SIGNED) AS `TOTAL_CREDITOS_N`,
    CAST(
        REPLACE(REPLACE(REPLACE(`INDICADOR CARTERA VENCIDA`, '%', ''), ' ', ''), ',', '.') 
    AS DECIMAL(5,2)) AS `PORCENTAJE_NUMERICO`
FROM icetxx.`comportamiento_de_cartera_y_crédito._20260814`;


ALTER TABLE icetxx.comportamiento_cartera_limpio
  DROP COLUMN `SALDO CAPITAL`,
  DROP COLUMN `SALDO TOTAL`,
  DROP COLUMN `SALDO MORA`,
  DROP COLUMN `CANTIDAD CREDITOS AL DIA`,
  DROP COLUMN `CANTIDAD CREDITOS CON MORA MENOR A 90 DIAS`,
  DROP COLUMN `CANTIDAD CREDITOS MORA MAYOR A 90 DIAS`,
  DROP COLUMN `TOTAL CREDITOS`,
  DROP COLUMN `INDICADOR CARTERA VENCIDA`;


ALTER TABLE icetxx.comportamiento_cartera_limpio
  RENAME COLUMN `SALDO_CAPITAL_NUMERICO` TO `SALDO CAPITAL`,
  RENAME COLUMN `SALDO_TOTAL_NUMERICO` TO `SALDO TOTAL`,
  RENAME COLUMN `SALDO_MORA_LIMPIO` TO `SALDO MORA`,
  RENAME COLUMN `CANTIDAD_CREDITO_AL_DIA_N` TO `CANTIDAD CREDITOS AL DIA`,
  RENAME COLUMN `CANTIDAD_CREDITOS_CON_MORA_MENOR_A_90_DIAS_N` TO `CANTIDAD CREDITOS CON MORA MENOR A 90 DIAS`,
  RENAME COLUMN `CANTIDAD_CREDITOS_MORA_MAYOR_A_90_DIAS_N` TO `CANTIDAD CREDITOS MORA MAYOR A 90 DIAS`,
  RENAME COLUMN `TOTAL_CREDITOS_N` TO `TOTAL CREDITOS`,
  RENAME COLUMN `PORCENTAJE_NUMERICO` TO `INDICADOR CARTERA VENCIDA`;

SET SQL_SAFE_UPDATES = 0;


UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = 'DISTRITO CAPITAL'
WHERE UPPER(REPLACE(`DEPTORESIDENCIA`, ' ', '')) = 'DISTRITOCAPITAL';
UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = 'VALLE DEL CAUCA'
WHERE UPPER(REPLACE(`DEPTORESIDENCIA`, ' ', '')) = 'VALLEDELCAUCA';
UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = 'SIN INFORMACION'
WHERE UPPER(`DEPTORESIDENCIA`) IN ('SIN_INFO','SININFORMACION',  'SIN INFO', 'SININFO', 'SIN INFORMACION');
UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = 'LA GUAJIRA'
WHERE UPPER(REPLACE(`DEPTORESIDENCIA`, ' ', '')) = 'LAGUAJIRA';
UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = 'NORTE DE SANTANDER'
WHERE UPPER(REPLACE(`DEPTORESIDENCIA`, ' ', '')) = 'NORTEDESANTANDER';
UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = 'SAN ANDRES'
WHERE UPPER(REPLACE(`DEPTORESIDENCIA`, ' ', '')) = 'SANANDRES';

UPDATE icetxx.comportamiento_cartera_limpio
SET `DEPTORESIDENCIA` = UPPER(TRIM(`DEPTORESIDENCIA`));

UPDATE icetxx.comportamiento_cartera_limpio
SET `EPOCA CARTERA` = UPPER(TRIM(`EPOCA CARTERA`));

SET SQL_SAFE_UPDATES = 1;

SELECT * FROM icetxx.comportamiento_cartera_limpio;